spring.application.name=BookDemo
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/bookdb
spring.datasource.username=root
spring.datasource.password=${LDBPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#eureka.client.service-url.defaultZone=http://localhost:8762/eureka

logging.level.root=warn
logging.level.org.springframework.web=debug
logging.level.org.hibernate=error


#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.disable-swagger-default-url=true